namespace Uncreated.Warfare.API.Items;

public enum ItemRedirect
{
    None = 0,
    Shirt,
    Pants,
    Vest,
    Hat,
    Mask,
    Backpack,
    Glasses,
    AmmoSupply,
    BuildSupply,
    RallyPoint,
    Radio,
    AmmoBag,
    AmmoCrate,
    RepairStation,
    Bunker,
    VehicleBay,
    EntrenchingTool,
    UAV,
    RepairStationBuilt,
    AmmoCrateBuilt,
    BunkerBuilt,
    Cache,
    RadioDamaged,
    LaserDesignator,
    StandardAmmoIcon,
    StandardMeleeIcon,
    StandardGrenadeIcon,
    StandardSmokeGrenadeIcon,
}