// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uncreated.Warfare.Database;

namespace Uncreated.Warfare.Migrations
{
    [DbContext(typeof(WarfareDbContext))]
    [Migration("20231129215138_UpdateFactionNullability")]
    partial class UpdateFactionNullability
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Uncreated.Warfare.Models.Factions.Faction", b =>
                {
                    b.Property<uint>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("pk")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("varchar(8) CHARACTER SET utf8mb4")
                        .HasMaxLength(8);

                    b.Property<string>("Emoji")
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4")
                        .HasMaxLength(64);

                    b.Property<string>("FlagImageUrl")
                        .IsRequired()
                        .HasColumnType("varchar(128) CHARACTER SET utf8mb4")
                        .HasMaxLength(128);

                    b.Property<string>("HexColor")
                        .IsRequired()
                        .HasColumnType("char(6)");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasColumnName("Id")
                        .HasColumnType("varchar(16) CHARACTER SET utf8mb4")
                        .HasMaxLength(16);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32) CHARACTER SET utf8mb4")
                        .HasMaxLength(32);

                    b.Property<string>("ShortName")
                        .HasColumnType("varchar(24) CHARACTER SET utf8mb4")
                        .HasMaxLength(24);

                    b.Property<int?>("SpriteIndex")
                        .HasColumnType("int");

                    b.Property<string>("UnarmedKit")
                        .HasColumnType("varchar(25) CHARACTER SET utf8mb4")
                        .HasMaxLength(25);

                    b.HasKey("Key");

                    b.ToTable("factions");
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Factions.FactionAsset", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("pk")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasColumnType("char(32)");

                    b.Property<uint>("FactionId")
                        .HasColumnName("Faction")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Redirect")
                        .IsRequired()
                        .HasColumnType("enum('Shirt','Pants','Vest','Hat','Mask','Backpack','Glasses','AmmoSupply','BuildSupply','RallyPoint','Radio','AmmoBag','AmmoCrate','RepairStation','Bunker','EntrenchingTool','UAV','RepairStationBuilt','AmmoCrateBuilt','BunkerBuilt','Cache','RadioDamaged','LaserDesignator')");

                    b.Property<string>("VariantKey")
                        .HasColumnType("varchar(32) CHARACTER SET utf8mb4")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.ToTable("faction_assets");
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Factions.FactionLocalization", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("pk")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("varchar(8) CHARACTER SET utf8mb4")
                        .HasMaxLength(8);

                    b.Property<uint>("FactionId")
                        .HasColumnName("Faction")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("LanguageId")
                        .HasColumnName("Language")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(32) CHARACTER SET utf8mb4")
                        .HasMaxLength(32);

                    b.Property<string>("ShortName")
                        .HasColumnType("varchar(24) CHARACTER SET utf8mb4")
                        .HasMaxLength(24);

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.HasIndex("LanguageId");

                    b.ToTable("faction_translations");
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.Bundles.EliteBundle", b =>
                {
                    b.Property<uint>("PrimaryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("pk")
                        .HasColumnType("int unsigned");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<uint?>("FactionId")
                        .HasColumnName("Faction")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("varchar(25) CHARACTER SET utf8mb4")
                        .HasMaxLength(25);

                    b.HasKey("PrimaryKey");

                    b.HasIndex("FactionId");

                    b.ToTable("kits_bundles");
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.Bundles.KitEliteBundle", b =>
                {
                    b.Property<uint>("KitId")
                        .HasColumnName("Kit")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("BundleId")
                        .HasColumnName("Bundle")
                        .HasColumnType("int unsigned");

                    b.HasKey("KitId", "BundleId");

                    b.HasIndex("BundleId");

                    b.ToTable("kits_bundle_items");
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.Kit", b =>
                {
                    b.Property<uint>("PrimaryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("pk")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("enum('Infantry','Armor','Airforce','SpecOps','Navy')");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("enum('Unarmed','Squadleader','Rifleman','Medic','Breacher','AutomaticRifleman','Grenadier','MachineGunner','LAT','HAT','Marksman','Sniper','APRifleman','CombatEngineer','Crewman','Pilot','SpecOps')");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnName("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<ulong>("Creator")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("CreditCost")
                        .HasColumnType("int");

                    b.Property<bool>("Disabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("FactionFilterIsWhitelist")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint?>("FactionId")
                        .HasColumnName("Faction")
                        .HasColumnType("int unsigned");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasColumnName("Id")
                        .HasColumnType("varchar(25) CHARACTER SET utf8mb4")
                        .HasMaxLength(25);

                    b.Property<DateTime>("LastEditedTimestamp")
                        .HasColumnName("LastEditedAt")
                        .HasColumnType("datetime");

                    b.Property<ulong>("LastEditor")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("MapFilterIsWhitelist")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("PremiumCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<float>("RequestCooldown")
                        .HasColumnType("float");

                    b.Property<bool>("RequiresNitro")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<string>("SquadLevel")
                        .IsRequired()
                        .HasColumnType("enum('Member','Commander')");

                    b.Property<float?>("TeamLimit")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("enum('Public','Elite','Special','Loadout')");

                    b.Property<string>("WeaponText")
                        .HasColumnName("Weapons")
                        .HasColumnType("varchar(128) CHARACTER SET utf8mb4")
                        .HasMaxLength(128);

                    b.HasKey("PrimaryKey");

                    b.HasIndex("FactionId");

                    b.ToTable("kits");
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.KitAccess", b =>
                {
                    b.Property<uint>("KitId")
                        .HasColumnName("Kit")
                        .HasColumnType("int unsigned");

                    b.Property<ulong>("Steam64")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasColumnType("enum('Unknown','Credits','Event','Purchase','QuestReward')");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("GivenAt")
                        .HasColumnType("datetime");

                    b.HasKey("KitId", "Steam64");

                    b.ToTable("kits_access");
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.KitFavorite", b =>
                {
                    b.Property<uint>("KitId")
                        .HasColumnName("Kit")
                        .HasColumnType("int unsigned");

                    b.Property<ulong>("Steam64")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("KitId", "Steam64");

                    b.HasIndex("Steam64");

                    b.ToTable("kits_favorites");
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.KitFilteredFaction", b =>
                {
                    b.Property<uint>("KitId")
                        .HasColumnName("Kit")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("FactionId")
                        .HasColumnName("Faction")
                        .HasColumnType("int unsigned");

                    b.HasKey("KitId", "FactionId");

                    b.HasIndex("FactionId");

                    b.ToTable("kits_faction_filters");
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.KitFilteredMap", b =>
                {
                    b.Property<uint>("KitId")
                        .HasColumnName("Kit")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Map")
                        .HasColumnName("Map")
                        .HasColumnType("int unsigned");

                    b.HasKey("KitId", "Map");

                    b.ToTable("kits_map_filters");
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.KitHotkey", b =>
                {
                    b.Property<uint>("KitId")
                        .HasColumnName("Kit")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("Slot")
                        .HasColumnType("tinyint unsigned");

                    b.Property<ulong>("Steam64")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Item")
                        .HasColumnType("char(32)");

                    b.Property<string>("Page")
                        .IsRequired()
                        .HasColumnType("enum('Primary','Secondary','Hands','Backpack','Vest','Shirt','Pants','Storage','Area')");

                    b.Property<string>("Redirect")
                        .HasColumnType("enum('Shirt','Pants','Vest','Hat','Mask','Backpack','Glasses','AmmoSupply','BuildSupply','RallyPoint','Radio','AmmoBag','AmmoCrate','RepairStation','Bunker','EntrenchingTool','UAV','RepairStationBuilt','AmmoCrateBuilt','BunkerBuilt','Cache','RadioDamaged','LaserDesignator')");

                    b.Property<byte>("X")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Y")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("KitId", "Slot", "Steam64");

                    b.ToTable("kits_hotkeys");
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.KitItemModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("pk")
                        .HasColumnType("int unsigned");

                    b.Property<byte?>("Amount")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("ClothingSlot")
                        .HasColumnType("enum('Shirt','Pants','Vest','Hat','Mask','Backpack','Glasses')");

                    b.Property<string>("Item")
                        .HasColumnType("char(32)");

                    b.Property<uint>("KitId")
                        .HasColumnName("Kit")
                        .HasColumnType("int unsigned");

                    b.Property<byte[]>("Metadata")
                        .HasColumnType("varbinary(18)")
                        .HasMaxLength(18);

                    b.Property<string>("Page")
                        .HasColumnType("enum('Primary','Secondary','Hands','Backpack','Vest','Shirt','Pants','Storage','Area')");

                    b.Property<string>("Redirect")
                        .HasColumnType("enum('Shirt','Pants','Vest','Hat','Mask','Backpack','Glasses','AmmoSupply','BuildSupply','RallyPoint','Radio','AmmoBag','AmmoCrate','RepairStation','Bunker','EntrenchingTool','UAV','RepairStationBuilt','AmmoCrateBuilt','BunkerBuilt','Cache','RadioDamaged','LaserDesignator')");

                    b.Property<string>("RedirectVariant")
                        .HasColumnType("varchar(36) CHARACTER SET utf8mb4")
                        .HasMaxLength(36);

                    b.Property<byte?>("Rotation")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("X")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("Y")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("KitId");

                    b.ToTable("kits_items");
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.KitLayoutTransformation", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("pk")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("KitId")
                        .HasColumnName("Kit")
                        .HasColumnType("int unsigned");

                    b.Property<string>("NewPage")
                        .IsRequired()
                        .HasColumnType("enum('Primary','Secondary','Hands','Backpack','Vest','Shirt','Pants','Storage','Area')");

                    b.Property<byte>("NewRotation")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("NewX")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("NewY")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("OldPage")
                        .IsRequired()
                        .HasColumnType("enum('Primary','Secondary','Hands','Backpack','Vest','Shirt','Pants','Storage','Area')");

                    b.Property<byte>("OldX")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("OldY")
                        .HasColumnType("tinyint unsigned");

                    b.Property<ulong>("Steam64")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("KitId");

                    b.HasIndex("Steam64");

                    b.ToTable("kits_layouts");
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.KitSkillset", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("pk")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("KitId")
                        .HasColumnName("Kit")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("Level")
                        .HasColumnName("Level")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasColumnName("Skill")
                        .HasColumnType("enum('OVERKILL','SHARPSHOOTER','DEXTERITY','CARDIO','EXERCISE','DIVING','PARKOUR','SNEAKYBEAKY','VITALITY','IMMUNITY','TOUGHNESS','STRENGTH','WARMBLOODED','SURVIVAL','HEALING','CRAFTING','OUTDOORS','COOKING','FISHING','AGRICULTURE','MECHANIC','ENGINEER')");

                    b.HasKey("Id");

                    b.HasIndex("KitId");

                    b.ToTable("kits_skillsets");
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.KitTranslation", b =>
                {
                    b.Property<uint>("KitId")
                        .HasColumnName("Kit")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("LanguageId")
                        .HasColumnName("Language")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(32) CHARACTER SET utf8mb4")
                        .HasMaxLength(32);

                    b.HasKey("KitId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("kits_sign_text");
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.KitUnlockRequirement", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("pk")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<uint>("KitId")
                        .HasColumnName("Kit")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("KitId");

                    b.ToTable("kits_unlock_requirements");
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Localization.LanguageAlias", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("pk")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4")
                        .HasMaxLength(64);

                    b.Property<uint>("LanguageId")
                        .HasColumnName("Language")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("lang_aliases");
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Localization.LanguageContributor", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("pk")
                        .HasColumnType("int unsigned");

                    b.Property<ulong>("Contributor")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("LanguageId")
                        .HasColumnName("Language")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("lang_credits");
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Localization.LanguageCulture", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("pk")
                        .HasColumnType("int unsigned");

                    b.Property<string>("CultureCode")
                        .IsRequired()
                        .HasColumnType("varchar(16) CHARACTER SET utf8mb4")
                        .HasMaxLength(16);

                    b.Property<uint>("LanguageId")
                        .HasColumnName("Language")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("lang_cultures");
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Localization.LanguageInfo", b =>
                {
                    b.Property<uint>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("pk")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("char(5)");

                    b.Property<string>("DefaultCultureCode")
                        .HasColumnType("varchar(16) CHARACTER SET utf8mb4")
                        .HasMaxLength(16);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4")
                        .HasMaxLength(64);

                    b.Property<string>("FallbackTranslationLanguageCode")
                        .HasColumnType("char(5)");

                    b.Property<bool>("HasTranslationSupport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("NativeName")
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4")
                        .HasMaxLength(64);

                    b.Property<bool>("RequiresIMGUI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("SteamLanguageName")
                        .HasColumnType("varchar(32) CHARACTER SET utf8mb4")
                        .HasMaxLength(32);

                    b.HasKey("Key");

                    b.ToTable("lang_info");
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Localization.LanguagePreferences", b =>
                {
                    b.Property<ulong>("Steam64")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Culture")
                        .HasColumnType("varchar(16) CHARACTER SET utf8mb4")
                        .HasMaxLength(16);

                    b.Property<uint>("LanguageId")
                        .HasColumnName("Language")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime");

                    b.Property<bool>("UseCultureForCommandInput")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UseCultureForCmdInput")
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.HasKey("Steam64");

                    b.HasIndex("LanguageId");

                    b.ToTable("lang_preferences");
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Users.WarfareUserData", b =>
                {
                    b.Property<ulong>("Steam64")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4")
                        .HasMaxLength(30);

                    b.Property<string>("DisplayName")
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4")
                        .HasMaxLength(30);

                    b.Property<DateTime?>("FirstJoined")
                        .HasColumnType("datetime");

                    b.Property<byte[]>("LastHWID")
                        .HasColumnType("binary(20)");

                    b.Property<string>("LastIPAddress")
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime?>("LastJoined")
                        .HasColumnType("datetime");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4")
                        .HasMaxLength(30);

                    b.Property<string>("PermissionLevel")
                        .IsRequired()
                        .HasColumnType("enum('Member','Helper','TrialAdmin','Admin','Superuser')");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("varchar(48) CHARACTER SET utf8mb4")
                        .HasMaxLength(48);

                    b.Property<uint>("TotalSeconds")
                        .HasColumnType("int unsigned");

                    b.HasKey("Steam64");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Factions.FactionAsset", b =>
                {
                    b.HasOne("Uncreated.Warfare.Models.Factions.Faction", "Faction")
                        .WithMany("Assets")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Factions.FactionLocalization", b =>
                {
                    b.HasOne("Uncreated.Warfare.Models.Factions.Faction", "Faction")
                        .WithMany("Translations")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uncreated.Warfare.Models.Localization.LanguageInfo", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.Bundles.EliteBundle", b =>
                {
                    b.HasOne("Uncreated.Warfare.Models.Factions.Faction", "Faction")
                        .WithMany()
                        .HasForeignKey("FactionId");
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.Bundles.KitEliteBundle", b =>
                {
                    b.HasOne("Uncreated.Warfare.Models.Kits.Bundles.EliteBundle", "Bundle")
                        .WithMany("Kits")
                        .HasForeignKey("BundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uncreated.Warfare.Models.Kits.Kit", "Kit")
                        .WithMany("Bundles")
                        .HasForeignKey("KitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.Kit", b =>
                {
                    b.HasOne("Uncreated.Warfare.Models.Factions.Faction", "Faction")
                        .WithMany()
                        .HasForeignKey("FactionId");
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.KitAccess", b =>
                {
                    b.HasOne("Uncreated.Warfare.Models.Kits.Kit", "Kit")
                        .WithMany()
                        .HasForeignKey("KitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.KitFavorite", b =>
                {
                    b.HasOne("Uncreated.Warfare.Models.Kits.Kit", "Kit")
                        .WithMany()
                        .HasForeignKey("KitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.KitFilteredFaction", b =>
                {
                    b.HasOne("Uncreated.Warfare.Models.Factions.Faction", "Faction")
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uncreated.Warfare.Models.Kits.Kit", "Kit")
                        .WithMany("FactionFilter")
                        .HasForeignKey("KitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.KitFilteredMap", b =>
                {
                    b.HasOne("Uncreated.Warfare.Models.Kits.Kit", "Kit")
                        .WithMany("MapFilter")
                        .HasForeignKey("KitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.KitHotkey", b =>
                {
                    b.HasOne("Uncreated.Warfare.Models.Kits.Kit", "Kit")
                        .WithMany()
                        .HasForeignKey("KitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.KitItemModel", b =>
                {
                    b.HasOne("Uncreated.Warfare.Models.Kits.Kit", "Kit")
                        .WithMany("ItemModels")
                        .HasForeignKey("KitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.KitLayoutTransformation", b =>
                {
                    b.HasOne("Uncreated.Warfare.Models.Kits.Kit", "Kit")
                        .WithMany()
                        .HasForeignKey("KitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.KitSkillset", b =>
                {
                    b.HasOne("Uncreated.Warfare.Models.Kits.Kit", "Kit")
                        .WithMany("Skillsets")
                        .HasForeignKey("KitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.KitTranslation", b =>
                {
                    b.HasOne("Uncreated.Warfare.Models.Kits.Kit", "Kit")
                        .WithMany("Translations")
                        .HasForeignKey("KitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uncreated.Warfare.Models.Localization.LanguageInfo", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Kits.KitUnlockRequirement", b =>
                {
                    b.HasOne("Uncreated.Warfare.Models.Kits.Kit", "Kit")
                        .WithMany("UnlockRequirementsModels")
                        .HasForeignKey("KitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Localization.LanguageAlias", b =>
                {
                    b.HasOne("Uncreated.Warfare.Models.Localization.LanguageInfo", "Language")
                        .WithMany("Aliases")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Localization.LanguageContributor", b =>
                {
                    b.HasOne("Uncreated.Warfare.Models.Localization.LanguageInfo", "Language")
                        .WithMany("Contributors")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Localization.LanguageCulture", b =>
                {
                    b.HasOne("Uncreated.Warfare.Models.Localization.LanguageInfo", "Language")
                        .WithMany("SupportedCultures")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uncreated.Warfare.Models.Localization.LanguagePreferences", b =>
                {
                    b.HasOne("Uncreated.Warfare.Models.Localization.LanguageInfo", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
